name: corona_app

description: Corona app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  intl: ^0.16.0
  permission_handler: ^5.0.0+hotfix.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
        - family: Baloo
          fonts:
            - asset: assets/fonts/Baloo/Baloo-Regular.ttf
            - asset: assets/fonts/Baloo/Baloo-Bold.ttf


